const SQL_EJ = [
 {n:"Consulta base de clase",e:"Muestra nombre, apellido, departamento y años de antigüedad de los empleados que ganan más de 20.000, ordenados por departamento.",
  s:"SELECT first_name, last_name, department_name,\n       ROUND(MONTHS_BETWEEN(SYSDATE, hire_date)/12) AS antiguedad\nFROM employees JOIN departments USING(department_id)\nWHERE salary > 20000\nORDER BY department_name;",
  h:"USING solo funciona porque department_id se llama igual en ambas tablas. Fíjate que WHERE se aplica antes de ordenar."},
 {n:"Filtro + orden",e:"Lista nombre completo y sueldo de los empleados del departamento llamado 'IT', del sueldo más alto al más bajo.",
  s:"SELECT e.first_name || ' ' || e.last_name AS nombre, e.salary\nFROM employees e JOIN departments d ON e.department_id = d.department_id\nWHERE d.department_name = 'IT'\nORDER BY e.salary DESC;",
  h:"En Oracle se concatena con ||, no con CONCAT ni con +. Las comparaciones de texto distinguen mayúsculas."},
 {n:"Agrupación",e:"Cuenta cuántos empleados hay en cada departamento, mostrando el nombre del departamento.",
  s:"SELECT d.department_name, COUNT(e.employee_id) AS total\nFROM departments d LEFT JOIN employees e ON d.department_id = e.department_id\nGROUP BY d.department_name\nORDER BY total DESC;",
  h:"Con LEFT JOIN aparecen también los departamentos sin empleados (total 0). Con INNER JOIN esos desaparecen: es un clásico de pregunta con trampa."},
 {n:"HAVING",e:"Muestra los departamentos cuyo sueldo promedio supera los 8.000.",
  s:"SELECT department_id, ROUND(AVG(salary),2) AS promedio\nFROM employees\nGROUP BY department_id\nHAVING AVG(salary) > 8000;",
  h:"La condición sobre AVG va en HAVING, nunca en WHERE: cuando se evalúa el WHERE, los grupos todavía no existen."},
 {n:"Self-join",e:"Muestra el nombre de cada empleado junto al nombre de su jefe directo.",
  s:"SELECT e.first_name AS empleado, j.first_name AS jefe\nFROM employees e LEFT JOIN employees j\n  ON e.manager_id = j.employee_id;",
  h:"Dos alias sobre la misma tabla. Con LEFT JOIN también aparece el presidente, que no tiene jefe (jefe en NULL)."},
 {n:"JOIN encadenado",e:"Lista el nombre del empleado, su departamento y la ciudad donde trabaja.",
  s:"SELECT e.first_name, d.department_name, l.city\nFROM employees e\n  JOIN departments d ON e.department_id = d.department_id\n  JOIN locations   l ON d.location_id   = l.location_id;",
  h:"Para llegar de EMPLOYEES a LOCATIONS hay que pasar obligatoriamente por DEPARTMENTS: no existe FK directa."},
 {n:"Subconsulta",e:"Muestra los empleados que ganan más que el promedio general de la empresa.",
  s:"SELECT first_name, last_name, salary\nFROM employees\nWHERE salary > (SELECT AVG(salary) FROM employees);",
  h:"La subconsulta devuelve un único valor, por eso puede compararse con >. Si devolviera varias filas necesitarías IN o ANY."},
 {n:"Subconsulta correlacionada",e:"Muestra los empleados que ganan más que el promedio de su propio departamento.",
  s:"SELECT e.first_name, e.salary, e.department_id\nFROM employees e\nWHERE e.salary > (SELECT AVG(s.salary)\n                  FROM employees s\n                  WHERE s.department_id = e.department_id);",
  h:"Es correlacionada porque la subconsulta usa e.department_id de la consulta externa: se recalcula para cada fila."},
 {n:"NULL y NVL",e:"Muestra el sueldo total (sueldo + comisión sobre el sueldo) de cada empleado, tratando la comisión nula como cero.",
  s:"SELECT first_name,\n       salary + (salary * NVL(commission_pct, 0)) AS total\nFROM employees;",
  h:"Sin NVL, cualquier operación con NULL da NULL y perderías el sueldo de todos los que no tienen comisión."},
 {n:"DDL",e:"Crea la tabla CURSOS con id numérico como PK, nombre de texto obligatorio y una FK profesor_id hacia EMPLOYEES.",
  s:"CREATE TABLE cursos (\n  curso_id     NUMBER PRIMARY KEY,\n  nombre       VARCHAR2(100) NOT NULL,\n  profesor_id  NUMBER,\n  CONSTRAINT fk_curso_prof FOREIGN KEY (profesor_id)\n    REFERENCES employees(employee_id)\n);",
  h:"En Oracle es VARCHAR2, no VARCHAR. Nombrar la constraint (fk_curso_prof) es buena práctica y suele puntuar."},
 {n:"Vista",e:"Crea una vista que muestre solo nombre, cargo y departamento de los empleados, sin exponer sueldos.",
  s:"CREATE VIEW v_empleados_publico AS\nSELECT e.first_name, e.last_name, j.job_title, d.department_name\nFROM employees e\n  JOIN jobs j        ON e.job_id = j.job_id\n  JOIN departments d ON e.department_id = d.department_id;",
  h:"Este es el caso de uso típico de una vista en la prueba: restringir columnas sensibles sin tocar la tabla original."}
];
