const TABLAS = {
  REGIONS:{pk:["region_id"],fk:[],cols:["region_id","region_name"],
    desc:"Regiones geográficas. Es la punta de la cadena geográfica: no depende de nadie.",
    rel:["REGIONS (1) → (N) COUNTRIES · una región agrupa varios países"]},
  COUNTRIES:{pk:["country_id"],fk:["region_id"],cols:["country_id","country_name","region_id"],
    desc:"Países. Su PK es un código de texto corto (CL, US), no un número.",
    rel:["REGIONS (1) → (N) COUNTRIES","COUNTRIES (1) → (N) LOCATIONS"]},
  LOCATIONS:{pk:["location_id"],fk:["country_id"],cols:["location_id","street_address","postal_code","city","state_province","country_id"],
    desc:"Direcciones físicas donde la empresa tiene oficinas.",
    rel:["COUNTRIES (1) → (N) LOCATIONS","LOCATIONS (1) → (N) DEPARTMENTS"]},
  DEPARTMENTS:{pk:["department_id"],fk:["manager_id","location_id"],cols:["department_id","department_name","manager_id","location_id"],
    desc:"Departamentos de la empresa. Ojo: manager_id apunta a EMPLOYEES, o sea que dos tablas se referencian mutuamente.",
    rel:["LOCATIONS (1) → (N) DEPARTMENTS","DEPARTMENTS (1) → (N) EMPLOYEES","DEPARTMENTS.manager_id → EMPLOYEES.employee_id","DEPARTMENTS (1) → (N) JOB_HISTORY"]},
  JOBS:{pk:["job_id"],fk:[],cols:["job_id","job_title","min_salary","max_salary"],
    desc:"Catálogo de cargos con su rango salarial. Sirve para preguntas del tipo «¿quién gana fuera de su rango?».",
    rel:["JOBS (1) → (N) EMPLOYEES","JOBS (1) → (N) JOB_HISTORY"]},
  EMPLOYEES:{pk:["employee_id"],fk:["job_id","manager_id","department_id"],
    cols:["employee_id","first_name","last_name","email","phone_number","hire_date","job_id","salary","commission_pct","manager_id","department_id"],
    desc:"La tabla central. Tiene tres FK y una de ellas (manager_id) apunta a ella misma: relación reflexiva.",
    rel:["DEPARTMENTS (1) → (N) EMPLOYEES","JOBS (1) → (N) EMPLOYEES","EMPLOYEES.manager_id → EMPLOYEES.employee_id (reflexiva)","EMPLOYEES (1) → (N) JOB_HISTORY"]},
  JOB_HISTORY:{pk:["employee_id","start_date"],fk:["employee_id","job_id","department_id"],
    cols:["employee_id","start_date","end_date","job_id","department_id"],
    desc:"Historial de cargos anteriores. Su PK es compuesta (employee_id + start_date) porque un mismo empleado puede tener varios cargos, pero no dos que empiecen el mismo día.",
    rel:["EMPLOYEES (1) → (N) JOB_HISTORY","JOBS (1) → (N) JOB_HISTORY","DEPARTMENTS (1) → (N) JOB_HISTORY"]}
};
